In [219]:
import pandas as pd

In [220]:
complete_df = pd.read_csv('./train.csv')

In [221]:
complete_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [222]:
complete_df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

### Separating numerical and catergorical data

In [223]:
numerical_df = complete_df.select_dtypes(include=['int64', 'float64'])
numerical_df.drop('SalePrice', axis=1, inplace=True)
numerical_df.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,548,0,61,0,0,0,0,0,2,2008
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,460,298,0,0,0,0,0,0,5,2007
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,608,0,42,0,0,0,0,0,9,2008
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,642,0,35,272,0,0,0,0,2,2006
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,836,192,84,0,0,0,0,0,12,2008

In [224]:
category_df = complete_df.select_dtypes(include=['object'])
category_df.head()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1,RL,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
2,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
3,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Detchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Abnorml
4,RL,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal

### Handling null values in numerical data

In [225]:
#show the columns with missing values in nu
missing_values = numerical_df.isnull().sum()
missing_values = missing_values[missing_values > 0]
missing_values

LotFrontage    259
MasVnrArea       8
GarageYrBlt     81
dtype: int64

In [226]:
#fill the missing values with the mean of the column for numerical data
numerical_df = numerical_df.fillna(numerical_df.mean())

In [227]:
missing_values = numerical_df.isnull().sum()
missing_values = missing_values[missing_values > 0]
missing_values

Series([], dtype: int64)

which means there are no null values in numerical df now

### Handling missing values in categorical data

In [228]:
#show the colunms with missing values in category_df
missing_values = category_df.isnull().sum()
missing_values = missing_values[missing_values > 0]
missing_values

Alley           1369
MasVnrType       872
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1453
Fence           1179
MiscFeature     1406
dtype: int64

In [229]:
#drop the columns in category_df with a lot of missing values
category_df = category_df.drop(['Alley', 'MasVnrType', 'PoolQC','Fence','MiscFeature','FireplaceQu'], axis=1)

In [230]:
#show the columns with missing values in category_df
missing_values = category_df.isnull().sum()
missing_values = missing_values[missing_values > 0]
missing_values

BsmtQual        37
BsmtCond        37
BsmtExposure    38
BsmtFinType1    37
BsmtFinType2    38
Electrical       1
GarageType      81
GarageFinish    81
GarageQual      81
GarageCond      81
dtype: int64

In [231]:
#fill the missing values with the mode of the column for category data
category_df = category_df.fillna(category_df.mode().iloc[0])

In [232]:
numerical_df.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,548,0,61,0,0,0,0,0,2,2008
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,460,298,0,0,0,0,0,0,5,2007
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,608,0,42,0,0,0,0,0,9,2008
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,642,0,35,272,0,0,0,0,2,2006
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,836,192,84,0,0,0,0,0,12,2008

In [233]:
category_df.head()

,MSZoning,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,Electrical,KitchenQual,Functional,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,SaleType,SaleCondition
0,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,...,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
1,RL,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,...,SBrkr,TA,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
2,RL,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,...,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
3,RL,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,...,SBrkr,Gd,Typ,Detchd,Unf,TA,TA,Y,WD,Abnorml
4,RL,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,...,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal

### Encoding the categorical data

In [234]:
#do one hot encoding for the category data using SciKit Learn
from sklearn.preprocessing import OneHotEncoder

# One-hot encoding
encoder = OneHotEncoder(sparse=False)
encoded_array = encoder.fit_transform(category_df)

# Convert the array back to a DataFrame
encoded_df = pd.DataFrame(encoded_array, columns=encoder.get_feature_names_out(category_df.columns))
print(encoded_df)
category_df = encoded_df

      MSZoning_C (all)  MSZoning_FV  MSZoning_RH  MSZoning_RL  MSZoning_RM  \
0                  0.0          0.0          0.0          1.0          0.0
1                  0.0          0.0          0.0          1.0          0.0
2                  0.0          0.0          0.0          1.0          0.0
3                  0.0          0.0          0.0          1.0          0.0
4                  0.0          0.0          0.0          1.0          0.0
...                ...          ...          ...          ...          ...
1455               0.0          0.0          0.0          1.0          0.0
1456               0.0          0.0          0.0          1.0          0.0
1457               0.0          0.0          0.0          1.0          0.0
1458               0.0          0.0          0.0          1.0          0.0
1459               0.0          0.0          0.0          1.0          0.0

      Street_Grvl  Street_Pave  LotShape_IR1  LotShape_IR2  LotShape_IR3  ...  \
0             0.0          1.0           0.0           0.0           0.0  ...
1             0.0          1.0           0.0           0.0           0.0  ...
2             0.0          1.0           1.0           0.0           0.0  ...
3             0.0          1.0           1.0           0.0           0.0  ...
4             0.0          1.0           1.0           0.0           0.0  ...
...           ...          ...           ...           ...           ...  ...
1455          0.0          1.0           0.0           0.0           0.0  ...
1456          0.0          1.0           0.0           0.0           0.0  ...
1457          0.0          1.0           0.0           0.0           0.0  ...
1458          0.0          1.0           0.0           0.0           0.0  ...
1459          0.0          1.0           0.0           0.0           0.0  ...

      SaleType_ConLw  SaleType_New  SaleType_Oth  SaleType_WD  \
0                0.0           0.0           0.0          1.0
1                0.0           0.0           0.0          1.0
2                0.0           0.0           0.0          1.0
3                0.0           0.0           0.0          1.0
4                0.0           0.0           0.0          1.0
...              ...           ...           ...          ...
1455             0.0           0.0           0.0          1.0
1456             0.0           0.0           0.0          1.0
1457             0.0           0.0           0.0          1.0
1458             0.0           0.0           0.0          1.0
1459             0.0           0.0           0.0          1.0

      SaleCondition_Abnorml  SaleCondition_AdjLand  SaleCondition_Alloca  \
0                       0.0                    0.0                   0.0
1                       0.0                    0.0                   0.0
2                       0.0                    0.0                   0.0
3                       1.0                    0.0                   0.0
4                       0.0                    0.0                   0.0
...                     ...                    ...                   ...
1455                    0.0                    0.0                   0.0
1456                    0.0                    0.0                   0.0
1457                    0.0                    0.0                   0.0
1458                    0.0                    0.0                   0.0
1459                    0.0                    0.0                   0.0

      SaleCondition_Family  SaleCondition_Normal  SaleCondition_Partial
0                      0.0                   1.0                    0.0
1                      0.0                   1.0                    0.0
2                      0.0                   1.0                    0.0
3                      0.0                   0.0                    0.0
4                      0.0                   1.0                    0.0
...                    ...                   ...                    ...
1455                   0.0                   1.0                    0.0
1456                   0.0                   1.0                    0.0
1457                   0.0                   1.0                    0.0
1458                   0.0                   1.0                    0.0
1459                   0.0                   1.0                    0.0

[1460 rows x 230 columns]

c:\Users\tanay\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

### Normalising the df

In [235]:
#normalise the numerical data using SciKit Learn
from sklearn.preprocessing import MinMaxScaler
# Normalise the data
scaler = MinMaxScaler()
normalised_array = scaler.fit_transform(numerical_df)
# Convert the array back to a DataFrame
normalised_df = pd.DataFrame(normalised_array, columns=numerical_df.columns)
print(normalised_df)
numerical_df = normalised_df

            Id  MSSubClass  LotFrontage   LotArea  OverallQual  OverallCond  \
0     0.000000    0.235294     0.150685  0.033420     0.666667        0.500
1     0.000685    0.000000     0.202055  0.038795     0.555556        0.875
2     0.001371    0.235294     0.160959  0.046507     0.666667        0.500
3     0.002056    0.294118     0.133562  0.038561     0.666667        0.500
4     0.002742    0.235294     0.215753  0.060576     0.777778        0.500
...        ...         ...          ...       ...          ...          ...
1455  0.997258    0.235294     0.140411  0.030929     0.555556        0.500
1456  0.997944    0.000000     0.219178  0.055505     0.555556        0.625
1457  0.998629    0.294118     0.154110  0.036187     0.666667        1.000
1458  0.999315    0.000000     0.160959  0.039342     0.444444        0.625
1459  1.000000    0.000000     0.184932  0.040370     0.444444        0.625

      YearBuilt  YearRemodAdd  MasVnrArea  BsmtFinSF1  ...  GarageArea  \
0      0.949275      0.883333    0.122500    0.125089  ...    0.386460
1      0.753623      0.433333    0.000000    0.173281  ...    0.324401
2      0.934783      0.866667    0.101250    0.086109  ...    0.428773
3      0.311594      0.333333    0.000000    0.038271  ...    0.452750
4      0.927536      0.833333    0.218750    0.116052  ...    0.589563
...         ...           ...         ...         ...  ...         ...
1455   0.920290      0.833333    0.000000    0.000000  ...    0.324401
1456   0.768116      0.633333    0.074375    0.139972  ...    0.352609
1457   0.500000      0.933333    0.000000    0.048724  ...    0.177715
1458   0.565217      0.766667    0.000000    0.008682  ...    0.169252
1459   0.673913      0.250000    0.000000    0.147059  ...    0.194640

      WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  \
0       0.000000     0.111517       0.000000        0.0          0.0
1       0.347725     0.000000       0.000000        0.0          0.0
2       0.000000     0.076782       0.000000        0.0          0.0
3       0.000000     0.063985       0.492754        0.0          0.0
4       0.224037     0.153565       0.000000        0.0          0.0
...          ...          ...            ...        ...          ...
1455    0.000000     0.073126       0.000000        0.0          0.0
1456    0.407235     0.000000       0.000000        0.0          0.0
1457    0.000000     0.109689       0.000000        0.0          0.0
1458    0.427071     0.000000       0.202899        0.0          0.0
1459    0.858810     0.124314       0.000000        0.0          0.0

      PoolArea  MiscVal    MoSold  YrSold
0          0.0  0.00000  0.090909    0.50
1          0.0  0.00000  0.363636    0.25
2          0.0  0.00000  0.727273    0.50
3          0.0  0.00000  0.090909    0.00
4          0.0  0.00000  1.000000    0.50
...        ...      ...       ...     ...
1455       0.0  0.00000  0.636364    0.25
1456       0.0  0.00000  0.090909    1.00
1457       0.0  0.16129  0.363636    1.00
1458       0.0  0.00000  0.272727    1.00
1459       0.0  0.00000  0.454545    0.50

[1460 rows x 37 columns]

### Deciding the variables

In [236]:
y  = complete_df['SalePrice']
X = pd.concat([numerical_df, category_df], axis=1)
#remove the target column from the X

In [237]:
#show the correlation between the features and the target
correlation = X.corrwith(y)
correlation = correlation.sort_values(ascending=False)
print(correlation)

OverallQual          0.790982
GrLivArea            0.708624
GarageCars           0.640409
GarageArea           0.623431
TotalBsmtSF          0.613581
                       ...
GarageType_Detchd   -0.354141
BsmtQual_TA         -0.498545
GarageFinish_Unf    -0.513906
KitchenQual_TA      -0.519298
ExterQual_TA        -0.589044
Length: 267, dtype: float64

Including featrues with high correlation

In [238]:
#modify the features to only include the features with a correlation of 0.3 or higher
# X = X[correlation[correlation > 0.3].index]

In [239]:
#fit the data into a linear regression model dont do test train split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [240]:
# Create the model
model = LinearRegression()
# Fit the model
model.fit(X, y)

LinearRegression()

Taking in Test Data

In [264]:
#now take the test data and use it to predict the target
test_df = pd.read_csv('./test.csv')

Managing null values in test data

In [266]:
numerical_test_df = test_df.select_dtypes(include=['int64', 'float64'])
numerical_test_df = numerical_test_df.fillna(numerical_test_df.mean())

In [267]:
missing_values = numerical_test_df.isnull().sum()
missing_values = missing_values[missing_values > 0]
missing_values

Series([], dtype: int64)

### Handling missing values in categorical data

In [269]:
#select category data from test_df
category_test_df = test_df.select_dtypes(include=['object'])
category_test_df = category_test_df.drop(['Alley', 'MasVnrType', 'PoolQC','Fence','MiscFeature','FireplaceQu'], axis=1)

In [270]:
#show the columns with missing values in category_df
missing_values = category_test_df.isnull().sum()
missing_values = missing_values[missing_values > 0]
missing_values

MSZoning         4
Utilities        2
Exterior1st      1
Exterior2nd      1
BsmtQual        44
BsmtCond        45
BsmtExposure    44
BsmtFinType1    42
BsmtFinType2    42
KitchenQual      1
Functional       2
GarageType      76
GarageFinish    78
GarageQual      78
GarageCond      78
SaleType         1
dtype: int64

In [271]:
#fill the missing values with the mode of the column for category data
category_test_df = category_test_df.fillna(category_test_df.mode().iloc[0])

In [279]:
#ecnode the category data using the encoder from before
encoded_array = encoder.transform(category_test_df)
# Convert the array back to a DataFrame
encoded_df = pd.DataFrame(encoded_array, columns=encoder.get_feature_names_out(category_test_df.columns))

category_test_df = encoded_df

In [280]:
#normalise the numerical data using SciKit Learn
# Normalise the data
normalised_array = scaler.transform(numerical_test_df)
# Convert the array back to a DataFrame
normalised_df = pd.DataFrame(normalised_array, columns=numerical_test_df.columns)

numerical_test_df = normalised_df

In [282]:
X_test = pd.concat([numerical_test_df, category_test_df], axis=1)

In [283]:
# get the predictions from the model
predictions = model.predict(X_test)

In [285]:
# print the predictions
print(predictions[:5])

[1.31649340e+09 1.32506905e+09 1.32224331e+09 1.31594317e+09
 1.30316108e+09]

In [261]:
#save the predictions to a csv file with id, SalePrice and make sure they have equal number of rows
test_df['SalePrice'] = predictions
test_df['Id'] = test_df.index
test_df = test_df[['Id', 'SalePrice']]
test_df.to_csv('predictions.csv', index=False)